/*
  config.h - compile time configuration
  Part of Grbl
*/

#ifndef config_h
#define config_h
#include "grbl.h"

#define DEFAULTS_GENERIC
#define CPU_MAP_ATMEGA328P
#define BAUD_RATE 115200

#define CMD_RESET 0x18
#define CMD_STATUS_REPORT '?'
#define CMD_CYCLE_START '~'
#define CMD_FEED_HOLD '!'
#define CMD_SAFETY_DOOR 0x84
#define CMD_JOG_CANCEL  0x85
#define CMD_FEED_OVR_RESET 0x90
#define CMD_FEED_OVR_COARSE_PLUS 0x91
#define CMD_FEED_OVR_COARSE_MINUS 0x92
#define CMD_FEED_OVR_FINE_PLUS  0x93
#define CMD_FEED_OVR_FINE_MINUS  0x94
#define CMD_RAPID_OVR_RESET 0x95
#define CMD_RAPID_OVR_MEDIUM    0x96
#define CMD_RAPID_OVR_LOW       0x97
#define CMD_SPINDLE_OVR_RESET 0x99
#define CMD_SPINDLE_OVR_COARSE_PLUS 0x9A
#define CMD_SPINDLE_OVR_COARSE_MINUS 0x9B
#define CMD_SPINDLE_OVR_FINE_PLUS 0x9C
#define CMD_SPINDLE_OVR_FINE_MINUS 0x9D
#define CMD_SPINDLE_OVR_STOP 0x9E
#define CMD_COOLANT_FLOOD_OVR_TOGGLE 0xA0
#define CMD_COOLANT_MIST_OVR_TOGGLE 0xA1

#define HOMING_CYCLE_0 (1<<Z_AXIS)
#define HOMING_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS))
#define N_HOMING_LOCATE_CYCLE 1
#define HOMING_FORCE_SET_ORIGIN

#define N_STARTUP_LINE 2
#define N_DECIMAL_COORDVALUE_INCH 4
#define N_DECIMAL_COORDVALUE_MM   3
#define N_DECIMAL_RATEVALUE_INCH  1
#define N_DECIMAL_RATEVALUE_MM    0
#define N_DECIMAL_SETTINGVALUE    3
#define N_DECIMAL_RPMVALUE        0

// ==========================================
// 용량 확보를 위한 극단적 비활성화 섹션
// ==========================================

// 1. 원호 보간(G2, G3) 비활성화 - 가장 큰 효과
// #define ENABLE_ARC_SUPPORT // 주석 처리하여 비활성화

// 2. 프로빙(G38.x) 비활성화
// #define ENABLE_PROBE_SUPPORT // 주석 처리하여 비활성화

// 3. 고급 스텝 제어 비활성화
// #define ADAPTIVE_MULTI_AXIS_STEP_SMOOTHING 

// 4. 리미트 체크 및 안전 기능 축소
// #define CHECK_LIMITS_AT_INIT
// #define HOMING_INIT_LOCK

// 5. 보고서 필드 최소화
// #define REPORT_FIELD_BUFFER_STATE
// #define REPORT_FIELD_PIN_STATE
// #define REPORT_FIELD_CURRENT_FEED_SPEED
// #define REPORT_FIELD_WORK_COORD_OFFSET
// #define REPORT_FIELD_OVERRIDES
// #define REPORT_FIELD_LINE_NUMBERS

// 6. EEPROM 관리 기능 비활성화
// #define ENABLE_RESTORE_EEPROM_WIPE_ALL
// #define ENABLE_RESTORE_EEPROM_DEFAULT_SETTINGS
// #define ENABLE_RESTORE_EEPROM_CLEAR_PARAMETERS
// #define FORCE_BUFFER_SYNC_DURING_EEPROM_WRITE
// #define FORCE_BUFFER_SYNC_DURING_WCO_CHANGE

// 7. 기타 부가 기능 제거
// #define MESSAGE_PROBE_COORDINATES
// #define ENABLE_BUILD_INFO_WRITE_COMMAND
// #define RESTORE_OVERRIDES_AFTER_PROGRAM_END
// #define PARKING_ENABLE

#define SAFETY_DOOR_SPINDLE_DELAY 4.0
#define SAFETY_DOOR_COOLANT_DELAY 1.0
#define ACCELERATION_TICKS_PER_SECOND 100
#define TOOL_LENGTH_OFFSET_AXIS Z_AXIS
#define MINIMUM_JUNCTION_SPEED 0.0
#define MINIMUM_FEED_RATE 1.0
#define N_ARC_CORRECTION 12
#define ARC_ANGULAR_TRAVEL_EPSILON 5E-7
#define DWELL_TIME_STEP 50

// 필수 오버라이드 설정 추가
#define DEFAULT_FEED_OVERRIDE           100
#define MAX_FEED_RATE_OVERRIDE          200
#define MIN_FEED_RATE_OVERRIDE           10
#define FEED_OVERRIDE_COARSE_INCREMENT   10
#define FEED_OVERRIDE_FINE_INCREMENT      1

#define DEFAULT_RAPID_OVERRIDE  100
#define RAPID_OVERRIDE_MEDIUM    50
#define RAPID_OVERRIDE_LOW       25

#define DEFAULT_SPINDLE_SPEED_OVERRIDE    100
#define MAX_SPINDLE_SPEED_OVERRIDE        200
#define MIN_SPINDLE_SPEED_OVERRIDE         10
#define SPINDLE_OVERRIDE_COARSE_INCREMENT  10
#define SPINDLE_OVERRIDE_FINE_INCREMENT     1

// 필수 보고서 갱신 설정
#define REPORT_OVR_REFRESH_BUSY_COUNT 20
#define REPORT_OVR_REFRESH_IDLE_COUNT 10
#define REPORT_WCO_REFRESH_BUSY_COUNT 30
#define REPORT_WCO_REFRESH_IDLE_COUNT 10

#endif
